# Generated by Django 4.0 on 2022-03-09 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trans',
            name='trans_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
